version: "3.6"

services:
  api:
    image: volodymyrpastukh99/diploma:latest
    ports:
      - 80:8080
    expose:
      - 666
    depends_on:
     - database
    links:
     - database

  database:
      restart: always
      image: mongo:latest
      environment:
        - MONGO_INITDB_ROOT_USERNAME=campus
        - MONGO_INITDB_ROOT_PASSWORD=detitoorki
        - MONGO_INITDB_DATABASE=test
      ports:
        - 27017:27017
      expose:
        - 27017
